name: python-ci

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Koodi allalaadimine
        uses: actions/checkout@v2

      - name: Python'i installeerimine
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: installida sõltuvused
        run: pip install pytest

      - name: käivitada testid
        run: pytest
